// <auto-generated />
namespace InsuranceApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mig_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig_));
        
        string IMigrationMetadata.Id
        {
            get { return "201910112346128_Mig_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
